### ISSUE TITLE
Example for valid paper name

### ISSUE THREAD

**Issue by bugwelle** [Simsso/PDF-Paper-Manager#1]
Hi, 

what would be a valid filename for a paper so that it isn't listed as "Invalid paper file names:"? :-)

Regards,

Andre

**Comment by tpdenk** [comment]
from the tests:
`Battaglia et al. (2018) Relational inductive biases, deep learning, and graph networks [Google].pdf`

see https://github.com/Simsso/PDF-Paper-Manager/blob/master/test/parser.js#L7

**Comment by Simsso** [comment]
First, you two are nice! Thanks for the comments!

I have expanded the README [here](https://github.com/Simsso/PDF-Paper-Manager#pdf-paper-manager) by a brief description of the project and an informal specification of the paper naming convention.

Please close the issue if this answers the questions sufficiently well. 🙂

**Comment by bugwelle** [comment]
Thanks! :-)

Regards,
Andre
